root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/paytm/"
  bin = "./tmp/main"
  include_ext = ["go", "mod", "sum"]
  # Directories to exclude from watching
  exclude_dir = ["tmp", "vendor"]
  # Files to exclude from watching
  exclude_file = []
  # This command will be executed before every build command if not empty
  pre_build = ""
  # This command will be executed after every build command if not empty
  post_build = ""

[log]
  # Log level: debug, info, warn, error, off
  level = "info"

[color]
  # Enable colors in log
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[http]
  # Enable HTTP server to serve static files
  enabled = false
  # Port to listen on
  port = 8080
  # Root directory of static files
  root = "public"
